# Algorytm genetyczny
## Anna Urbala

In [1]:
import numpy as np
import random
import math

In [47]:
class GenAlg:
    def __init__(self, fun, n_var, n_population=1000, rand_min=-10, rand_max=10):
        self.fun = fun
        self.n_var = n_var
        self.n_population = n_population
        self.population = np.random.uniform(rand_min, rand_max, size=(n_population, n_var))
        
    def iterate(self, n_iterations=100):
        for i in range(n_iterations):
            mutated = self.mutation()
            children = self.crossover()
            current_population = np.concatenate((self.population, mutated, children))
            print("population", current_population)
            print("evaluated", self.evaluate(current_population))
            
    
    def mutation(self):
        p = np.random.permutation(self.n_population)
        mutated_size = math.floor(self.n_population*0.2)
        return self.population[p][0:mutated_size] + np.random.normal(0, 1, size=(mutated_size, self.n_var))
    
    def crossover(self):
        p = np.random.permutation(self.n_population)
        parents_size = math.floor(self.n_population*0.7)
        parents = self.population[p][0:parents_size]
        children = np.array([self.cross(parents[i], parents[i+1]) for i in range(0, parents_size-1, 2)])
        return children.reshape(len(children) * 2, self.n_var)
        
    @staticmethod
    def cross(parent1, parent2):
        i = random.randint(0, len(parent1)-1)
        child1 = np.concatenate((parent1[0:i],parent2[i:]))
        child2 = np.concatenate((parent2[0:i],parent1[i:]))
        return [child1, child2]
    
    def evaluate(self, population):
        outputs = list(map(self.fun, population))
        population_min = min(outputs)
        return outputs - population_min + 0.1
    
    def selection(self):
        pass
        

In [10]:
def r3(elem):
    x,y,z = elem
    return x**2 + y**2 + 2*z**2

In [48]:
genalg = GenAlg(r3, 3, 10)
genalg.iterate(3)

population [[ -2.44370932   1.92944739   6.69765636]
 [ -4.14417637   8.87769273   7.25521825]
 [ -1.94415445   3.71112345   4.76643381]
 [ -6.26885626   9.15897925  -0.90882891]
 [ -3.11536435   3.69834675   3.98680606]
 [  3.6384043   -4.17751187  -1.40348179]
 [ -7.81484397   2.47988175  -1.08418312]
 [ -6.40617537   5.62072627   8.39625786]
 [  3.4733077    5.64682212  -1.84779213]
 [ -9.14973193  -8.59496915   1.20658905]
 [-10.10753753  -8.95541183   1.28736636]
 [ -8.58872172   2.75927803  -1.22393706]
 [  3.6384043   -4.17751187  -1.08418312]
 [ -7.81484397   2.47988175  -1.40348179]
 [ -3.11536435   1.92944739   6.69765636]
 [ -2.44370932   3.69834675   3.98680606]
 [ -6.40617537   5.62072627  -1.84779213]
 [  3.4733077    5.64682212   8.39625786]]
evaluated [6.64711865e+01 1.68323512e+02 3.00494589e+01 9.18969024e+01
 2.22320114e+01 1.68861623e+00 3.66320085e+01 1.80685442e+02
 1.78386407e+01 1.27562306e+02 1.52735843e+02 5.14353025e+01
 1.00000000e-01 3.82206248e+01 7.020496